// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PricesService.Data;

#nullable disable

namespace PricesService.Data.Migrations
{
    [DbContext(typeof(PricesServiceDbContext))]
    [Migration("20260519170003_PriceTextFields")]
    partial class PriceTextFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PricesService.Data.Entities.PriceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar")
                        .HasColumnName("id");

                    b.Property<string>("PriceText")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("price_text");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("product_id");

                    b.Property<string>("QuantityText")
                        .HasColumnType("varchar")
                        .HasColumnName("quantity_text");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sale_date");

                    b.Property<string>("SaleText")
                        .HasColumnType("varchar")
                        .HasColumnName("sale_text");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("store_id");

                    b.Property<string>("UnitPriceText")
                        .HasColumnType("varchar")
                        .HasColumnName("unit_price_text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_prices_product_id");

                    b.HasIndex("ProductId", "StoreId")
                        .IsUnique()
                        .HasDatabaseName("UX_prices_product_store");

                    b.ToTable("prices", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
